import { motion } from 'framer-motion';
import { recommendations } from '@/lib/mockData';
import { CheckCircle2 } from 'lucide-react';

const borderColors: Record<string, string> = {
  'High Priority': '#00E5A0',
  'Consider': '#3B82F6',
};

const RebalancingPlan = () => (
  <motion.div
    initial={{ opacity: 0, y: 24 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    transition={{ duration: 0.4, delay: 0.24 }}
    className="relative rounded-[20px] p-6 overflow-hidden"
    style={{
      background: 'linear-gradient(135deg, rgba(0,229,160,0.08) 0%, rgba(13,25,48,0.95) 40%, rgba(7,13,26,0.98) 100%)',
      border: '1px solid rgba(0,229,160,0.2)',
      boxShadow: '0 4px 24px rgba(0,0,0,0.4)',
    }}
  >
    {/* Corner glow */}
    <div className="absolute top-0 right-0 w-[60px] h-[60px] pointer-events-none"
      style={{ background: 'radial-gradient(circle at top right, rgba(0,229,160,0.15), transparent 70%)' }}
    />

    <h3 className="card-section-header mb-6">YOUR PERSONAL ACTION PLAN</h3>

    <div className="space-y-4 ml-[18px]">
      {recommendations.map((rec, i) => (
        <motion.div
          key={i}
          initial={{ x: -20, opacity: 0 }}
          whileInView={{ x: 0, opacity: 1 }}
          viewport={{ once: true }}
          transition={{ type: 'spring', stiffness: 400, damping: 40, delay: i * 0.15 }}
          className="flex gap-3 p-4 rounded-xl hover:bg-white/[0.07] transition-colors duration-200"
          style={{
            background: 'rgba(255,255,255,0.04)',
            borderLeft: `3px solid ${borderColors[rec.priority] || '#F59E0B'}`,
          }}
        >
          <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <span className={`inline-flex px-2.5 py-0.5 rounded-full text-[10px] font-body font-medium mb-1.5 ${
              rec.priority === 'High Priority' ? 'bg-primary/15 text-primary border border-primary/20' : 'bg-accent-blue/15 text-accent-blue border border-accent-blue/20'
            }`}>
              {rec.priority}
            </span>
            <p className="font-body text-[15px] text-foreground leading-relaxed">{rec.action}</p>
            <p className="font-body text-[13px] text-white/50 mt-1">{rec.reason}</p>
          </div>
        </motion.div>
      ))}
    </div>

    <div className="mt-8 pt-4 border-t border-white/5 ml-[18px]">
      <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md text-[11px] font-body text-primary border border-primary/15"
        style={{ background: 'rgba(0,229,160,0.08)' }}
      >
        ✦ Generated by FolioX AI · Not SEBI-registered advice
      </span>
    </div>
  </motion.div>
);

export default RebalancingPlan;
