import { motion } from 'framer-motion';
import { recommendations } from '@/lib/mockData';
import { CheckCircle2 } from 'lucide-react';

const borderColors: Record<string, string> = {
  'High Priority': '#00E5A0',
  'Consider': '#3B82F6',
};

const RebalancingPlan = () => (
  <motion.div
    initial={{ opacity: 0, y: 24 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    transition={{ duration: 0.4, delay: 0.24 }}
    className="relative rounded-[20px] p-6 overflow-hidden glass-card border-primary/20"
    style={{
      background: 'linear-gradient(180deg, rgba(0,229,160,0.1), transparent 100%), var(--bg-card)',
      backdropFilter: 'blur(20px)',
    }}
  >
    {/* Corner glow */}
    <div className="absolute top-0 right-0 w-[60px] h-[60px] pointer-events-none"
      style={{
        background: 'var(--bg-card)',
        backdropFilter: 'blur(20px)',
        borderColor: 'rgba(0,229,160,0.4)',
      }}
    />

    <h3 className="card-section-header mb-6">YOUR PERSONAL ACTION PLAN</h3>

    <div className="space-y-4 ml-[18px]">
      {recommendations.map((rec, i) => (
        <motion.div
          key={i}
          initial={{ x: -20, opacity: 0 }}
          whileInView={{ x: 0, opacity: 1 }}
          viewport={{ once: true }}
          transition={{ type: 'spring', stiffness: 400, damping: 40, delay: i * 0.15 }}
          className="flex gap-3 p-4 rounded-xl hover:bg-foreground/5 transition-colors duration-200 bg-foreground/5"
          style={{
            borderLeft: `3px solid ${borderColors[rec.priority] || '#F59E0B'}`,
          }}
        >
          <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <span className={`inline-flex px-2.5 py-0.5 rounded-full text-[10px] font-body font-medium mb-1.5 ${
              rec.priority === 'High Priority' ? 'bg-primary/15 text-primary border border-primary/20' : 'bg-accent-blue/15 text-accent-blue border border-accent-blue/20'
            }`}>
              {rec.priority}
            </span>
            <p className="font-body text-[15px] text-foreground leading-relaxed">{rec.action}</p>
            <p className="font-body text-[13px] text-muted-foreground mt-1">{rec.reason}</p>
          </div>
        </motion.div>
      ))}
    </div>

    <div className="mt-8 pt-4 border-t border-border/40 ml-[18px]">
      <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md text-[11px] font-body text-primary border border-primary/15 bg-primary/10"
      >
        ✦ Generated by FolioX AI · Not SEBI-registered advice
      </span>
    </div>
  </motion.div>
);

export default RebalancingPlan;
