import { motion } from 'framer-motion';
import { recommendations } from '@/lib/mockData';
import { CheckCircle2 } from 'lucide-react';

const RebalancingPlan = () => (
  <motion.div
    initial={{ opacity: 0, y: 12 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    className="bg-bg-dark rounded-xl border border-white/5 p-6 shadow-[0_2px_12px_rgba(0,0,0,0.06)]"
  >
    <h3 className="font-body text-lg font-bold text-primary-foreground mb-6">Your Personal Action Plan</h3>

    <div className="space-y-5">
      {recommendations.map((rec, i) => (
        <motion.div
          key={i}
          initial={{ opacity: 0, x: -12 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ delay: i * 0.1 }}
          className="flex gap-3"
        >
          <CheckCircle2 className="w-5 h-5 text-accent flex-shrink-0 mt-0.5" />
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className={`inline-flex px-2.5 py-0.5 rounded-full text-[10px] font-body font-medium ${
                rec.priority === 'High Priority' ? 'bg-accent/20 text-accent' : 'bg-white/10 text-white/60'
              }`}>
                {rec.priority}
              </span>
            </div>
            <p className="font-body text-[15px] text-primary-foreground leading-relaxed">{rec.action}</p>
            <p className="font-body text-[13px] text-white/60 mt-1">{rec.reason}</p>
          </div>
        </motion.div>
      ))}
    </div>

    <p className="font-body text-[11px] text-white/40 mt-8 pt-4 border-t border-white/5">
      Generated by FolioX AI · Not SEBI-registered advice
    </p>
  </motion.div>
);

export default RebalancingPlan;
